using ICSharpCode.Decompiler;
using ICSharpCode.Decompiler.CSharp;
using ICSharpCode.Decompiler.Metadata;
using ICSharpCode.Decompiler.TypeSystem;

namespace MadModStudio.ModAnalysis.Decompilation;

public sealed record DecompiledSource(bool Success, string Text, string? Error)
{
    public const string Banner =
        "// ============================================================================\n" +
        "//  DECOMPILED / RECONSTRUCTED SOURCE — NOT THE ORIGINAL SOURCE CODE\n" +
        "//  Generated by Mad Mod Studio from compiled IL using ICSharpCode.Decompiler.\n" +
        "//  Names, comments and structure may differ from the author's original.\n" +
        "// ============================================================================\n\n";
}

/// <summary>
/// Reconstructs C# from IL with ICSharpCode.Decompiler. The decompiler reads metadata/IL as data; the target assembly
/// is never loaded for execution.
/// </summary>
public sealed class DecompilerService
{
    public DecompiledSource DecompileType(string assemblyPath, string typeFullName, IEnumerable<string>? searchDirectories = null)
    {
        try
        {
            using var module = Open(assemblyPath);
            var decompiler = Create(module, assemblyPath, searchDirectories);
            var text = decompiler.DecompileTypeAsString(new FullTypeName(typeFullName.Replace('+', '/')));
            return new DecompiledSource(true, DecompiledSource.Banner + text, null);
        }
        catch (Exception ex)
        {
            return new DecompiledSource(false, "", $"Decompilation failed: {ex.Message}");
        }
    }

    public DecompiledSource DecompileAssembly(string assemblyPath, IEnumerable<string>? searchDirectories = null)
    {
        try
        {
            using var module = Open(assemblyPath);
            var decompiler = Create(module, assemblyPath, searchDirectories);
            var text = decompiler.DecompileWholeModuleAsString();
            return new DecompiledSource(true, DecompiledSource.Banner + text, null);
        }
        catch (Exception ex)
        {
            return new DecompiledSource(false, "", $"Decompilation failed: {ex.Message}");
        }
    }

    // Whole images are read into memory so no file handle or memory map is left on the assembly (or on the game's
    // DLLs resolved as references), which would otherwise lock the game folder until garbage collection.
    private static PEFile Open(string assemblyPath) => new(assemblyPath, System.Reflection.PortableExecutable.PEStreamOptions.PrefetchEntireImage);

    private static CSharpDecompiler Create(PEFile module, string assemblyPath, IEnumerable<string>? searchDirectories)
    {
        var settings = new DecompilerSettings(LanguageVersion.CSharp7_3)
        {
            ThrowOnAssemblyResolveErrors = false,
            LoadInMemory = true,
        };
        var resolver = new UniversalAssemblyResolver(assemblyPath, false, module.DetectTargetFrameworkId(),
            streamOptions: System.Reflection.PortableExecutable.PEStreamOptions.PrefetchEntireImage);
        resolver.AddSearchDirectory(Path.GetDirectoryName(Path.GetFullPath(assemblyPath))!);
        if (searchDirectories != null)
            foreach (var d in searchDirectories.Where(Directory.Exists)) resolver.AddSearchDirectory(d);
        return new CSharpDecompiler(module, resolver, settings);
    }
}
